### ISSUE TITLE
Can no longer expand Dice Rolls in Chat.

### ISSUE THREAD

**Issue by Brimcon** [trev33b/dice-tooltip2#7] opened 2022-02-09 03:37 UTC
With Tooltip enabled clicking on a chat card with an item roll makes this appear on the cursor and moves along with it.
![image](https://user-images.githubusercontent.com/7198283/153116819-3d7de455-3c72-429a-913c-df51748ebbe1.png)

It only appears for the latest item card after clicking attack or damage. All previous chat cards lose this functionality.

To reproduce, Click on an item roll on any character sheet (In this case, a Light Crossbow but will occur with any attack/Damage)
Click on the Dice roll. Observe dice rolls on the mouse cursor.
Attempt to roll another attack. Then try to click on the previous attack or damage roll.
![image](https://user-images.githubusercontent.com/7198283/153117189-399356c3-ab6a-4579-8a67-a51f747a7b1b.png)
This is default behaivor without Dice Tooltip enabled.

Foundry Version 9.249
DnD5e 1.5.7
DiceTooltip 2.2.2

**Comment by trev33b** [comment] 2022-02-14 07:00
I've reproduced this.   Looks like there's a stylesheet issue.  The chat log is used a style class called "dice-tooltip", which I'm also using for my tooltip.   I'll try making mine more unique.

**Comment by trev33b** [comment] 2022-02-14 07:14
Fixed in 2.3.0

**Closed by trev33b** 2022-02-14 07:14 UTC
