### ISSUE TITLE
Console Error on Spells with Saving Throw AND Damage - foruma.replace is not a function

### ISSUE THREAD

**Issue by eccobold** [trev33b/dice-tooltip2#2] opened 2022-02-04 06:29 UTC
While Actions of Type "Ranged Spell Attack" work fine, Actions of Type "Saving Throw" with a damage formula attached do raise console-errors and do not show a tooltip.

Examples: 
Command (Save without dmg > fine)
Eldrith Blast (Ranged Spell Attack with dmg > fine)
Mind Sliver (Save with dmg > Error)

![image](https://user-images.githubusercontent.com/71939920/152482857-3d22cb2f-6b3e-4c1f-95e7-8c735dbcb691.png)

**Comment by trev33b** [comment] 2022-02-04 19:34
Thanks for reporting this.  I'll take a look at it

**Comment by trev33b** [comment] 2022-02-06 02:15
I wasn't able to reproduce this.  I tested using the SRD versions of Command and Eldritch Blast, which both worked as you mentioned.  For Mind Sliver, since it wasn't part of the SRD, I used the VTTA D&D Beyond Integration to import it.  The spell details looked correct and I was able to see the expected tooltip without any errors showing in the console.

If you created Mind Sliver through a different importer (such as MrPrimate's D&D Beyond Importer), it's possible the spell has a different data description and maybe that's the cause.   

There may also be an issue with your actor or spell data.  Looking at the javascript stack trace, it's complaining about not finding a function called formula.replace().  Within dice-tooltip's rollFakeDamage function, it retrieves a "formula" object from the actor/item data and passes it down to the Item5e._scaleCantripDamage() function.   It's possible the formula object is incomplete and/or there's a 5e system version change that's the culprit.

To help me debug this, can you provide me the following information:
- What version of the D&D 5e system you are using (See General information in upper far right tab in Foundry)
- What version of Foundry you are using  (See General information in upper far right tab in Foundry)
- A JSON copy of Mind Sliver spell item (see below for how)
- A JSON copy of the actor that has this spell (see below for how)

To export the requested JSON data, go to the Actors and Items Foundry tabs in the upper right.  Find the actor/item you want to export, right-click it, and choose "Export Data".

**Comment by eccobold** [comment] 2022-02-06 08:40
thank you for looking into that. unfortunately I cannot provide further details until I return from holiday. I will check the spells setup as soon as I can.

**Comment by trev33b** [comment] 2022-02-06 09:14
Sure, no rush.

**Comment by DivertedCircle** [comment] 2022-02-09 17:28
I'm seeing the same error, and not just on spells with Saving Throws AND Damage formulas. Running DND 5e v1.5.7 on Foundry version 9, build 249. Actor JSON and 2 different spell JSON's are linked. The only modules enabled at the time were Tidy5e Sheet, Tidy UI - Game Settings, Module Sets - Dual Track GMing, and Dice Tooltip.

[https://drive.google.com/file/d/1A3f0OZHpMMJaGmnvT4LxE9_gxCiYyE1y/view?usp=sharing](https://drive.google.com/file/d/1A3f0OZHpMMJaGmnvT4LxE9_gxCiYyE1y/view?usp=sharing)
[https://drive.google.com/file/d/17TIpzZ-YFx_4MGy5niLCE3Rfl1OIZGs1/view?usp=sharing](https://drive.google.com/file/d/17TIpzZ-YFx_4MGy5niLCE3Rfl1OIZGs1/view?usp=sharing)
[https://drive.google.com/file/d/1SDMALFJnjp5R1UJM7vWh59nNH-zyDbDP/view?usp=sharing](https://drive.google.com/file/d/1SDMALFJnjp5R1UJM7vWh59nNH-zyDbDP/view?usp=sharing)

**Comment by trev33b** [comment] 2022-02-09 18:57
Thanks @DivertedCircle.  I'll take a look at this when I get a chance.

**Comment by eccobold** [comment] 2022-02-13 13:31
Hi @trev33b, I'm getting this error only with spells that have "level scaling" set to "cantrip" like:
![image](https://user-images.githubusercontent.com/71939920/153755433-e653d0b7-305d-4a36-8450-9b55929d3a32.png)

**Comment by trev33b** [comment] 2022-02-14 06:56
I've reproduced the issue with @DivertedCircle's sample data.   I also confirmed @eccobold's assertion about the Cantrip-based level scaling.

I tracked this down to an DND5e system API change that occurred in DND5e system 0.95.

I have a fix for this that will be appear in the next release.  I'll close this issue when I've issued the release.

**Comment by trev33b** [comment] 2022-02-14 07:15
Fixed in 2.3.0

**Closed by trev33b** 2022-02-14 07:15 UTC
